---
# The playbook defines how to configure all
# Rugby services

- hosts: db
  roles:
    - { role: db, when: db_type == 'MongoDB' } 

- hosts: lang
  roles:
    - { role: lang, when: lang_type == 'NodeJS' }

