---
# The playbook defines how to configure all
# Rugby services

- hosts: db
  roles:
    - { role: mongodb, when: db_type == 'MongoDB' } 

- hosts: lang
  roles:
    - { role: nodejs, when: lang_name == 'NodeJS' }

